### ISSUE TITLE
Fira Ligatures not working 

### ISSUE THREAD

**Issue by Ashtonian** [Gaafar/dev-fonts#14]
![image](https://user-images.githubusercontent.com/4212452/99840428-2986ee80-2b32-11eb-80e5-266228065a1b.png)

**Comment by Gaafar** [comment]
Seems that the whole font did not load for you. Can you clear cache & refresh and see if it persists?

**Comment by Ashtonian** [comment]
@Gaafar yes, you are correct, it was being blocked by a dns blocklist. Thank you! great site :)
